# -*- coding: utf-8 -*-
"""IPhone Sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OGw7h12JK3tysHhDZaNta-E_7t1Lo4Wx

#IPHONE SALES ANALYSIS
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

data=pd.read_csv("apple_products.csv")

data

#to check whwether the data is correct or not or missing
print(data.isnull().sum())

#to get statistical value
print(data.describe())

"""#I phone Sales In India"""

#to get top 10 or higher values
highest_rated= data.sort_values(by=["Star Rating"],ascending=False)
highest_rated=highest_rated.head(10)
print(highest_rated['Product Name'])

"""#Number of Highest Rating I phone On Flipkard"""

iphones=highest_rated["Product Name"].value_counts()
labels=iphones.index
counts=highest_rated["Number Of Ratings"]
figure=px.bar(highest_rated,x=labels,y=counts,title="No.of ratings of highest rated i phones")
figure.show()

iphones=highest_rated["Product Name"].value_counts()
labels=iphones.index
counts=highest_rated["Number Of Reviews"]
figure=px.bar(highest_rated,x=labels,y=counts,title="No.of reviw of highest rated i phones")
figure.show()

figure = px.scatter(data_frame=data, x="Number Of Ratings", y="Sale Price", size="Discount Percentage", trendline="ols", title="relationship between sales price and number of rating")
figure.show()

figure=px.scatter(data_frame=data,x="Number Of Ratings",y="Discount Percentage",size="Sale Price",trendline="ols",title="relation between discount price and number of ratings")
figure.show()